language: node_js
node_js:
- node
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:coverage
        - npm run coveralls
    - stage: tag release
      if: branch =~ ^release\/.*$ AND tag IS blank
      before_script:
        - git config --global push.default simple
      script:
        - npm version patch -m "Bump Version %s"
        - git log -1
        - #git push --tags https://${GITHUB_TOKEN}@github.com/tjoussen/redux-helper.git
    - stage: npm release
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          repo: tjoussen/redux-helper
