language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run test:coverage
- npm run coveralls

jobs:
  include:
    - stage: tag release
      node_js: "node"
      script:
        - npm version patch
      branches:
        only:
            - /^release\/.*$/
    - stage: npm release
      if: tag IS present
      node_js: "node"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          repo: tjoussen/redux-helper
