language: node_js
node_js:
- node
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:coverage
        - npm run coveralls
    - stage: tag release
      if: branch =~ /^release\/.*$/
      script:
        - npm version patch
    - stage: npm release
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          repo: tjoussen/redux-helper
